[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "10.30.96.48"
port = 5550

[conditions]
reference = "/home/sonhoanghguyen/Projects/readuntil/simulation/npgraph/assembly_graph.mmi"

[conditions.0]
name = "select_npgraph"
control = false
min_chunks = 0
max_chunks = inf
useful = "proceed"
useless = "unblock"
no_seq = "proceed"
no_map = "proceed"
